import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Links } from "./_components/links";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Brain Body Routine App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center gap-y-5">
          <div className="flex justify-center items-center sticky top-0 dark:bg-black/70 w-full"><Links /></div>
          <div className="flex w-full justify-center max-w-2xl">{children}</div>
        </main>
      </body>
    </html>
  );
}
