import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Links } from './_components/links'
import { SessionProvider } from 'next-auth/react'
import AuthProvider from './context/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Brain Body Routine App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <AuthProvider>
        <body className={`flex flex-col items-center h-full `}>
          <main className='flex flex-col w-full max-w-2xl h-full '>
            <div className='flex flex-col items-center justify-center w-full h-30 sticky top-0 z-30'>
              <Links className='topnavi h-full flex flex-col w-full gap-2 pt-1 pb-1 pl-8 pr-8 justify-center items-center  z-10 ' />
            </div>
            <div className='flex flex-col w-full h-full justify-center max-w-2xl items-center'>
              {children}
            </div>
          </main>
        </body>
      </AuthProvider>
    </html>
  )
}
